name: verbsTesting
description: Flutter application to test verbs.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

# Before using this application, ensure that your Flutter SDK, Dart SDK, and
# Android Studio are up to date.
dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.1
  at_onboarding_flutter: ^1.0.0+4
  at_client_mobile:
    git:
      url: https://github.com/atsign-foundation/at_client_sdk.git
      path: at_client_mobile
      ref: connection_issue
      version: ^1.0.1+10
  cupertino_icons: ^0.1.3
  modal_progress_hud: any
  at_demo_data: ^0.0.3+1
  fluttertoast: ^8.0.7
  intl: ^0.17.0
dependency_overrides:
  at_client_mobile:
    path: /Users/shris/Documents/shris/@company/notify_changes/at_client_sdk/at_client_mobile
  at_client:
    path: /Users/shris/Documents/shris/@company/notify_changes/at_client_sdk/at_client
  at_onboarding_flutter:
    git:
      url: https://github.com/atsign-foundation/at_widgets.git
      path: at_onboarding_flutter
      ref: namespace_revert
      version: ^2.0.0
  at_backupkey_flutter:
    git:
      url: https://github.com/atsign-foundation/at_widgets.git
      path: at_backupkey_flutter
      ref: namespace_revert
      version: ^2.0.0
  at_lookup:
    git:
      url: https://github.com/atsign-foundation/at_libraries.git
      path: at_lookup
      ref: sdk_refactoring
      version: ^2.0.1
  at_server_status:
    git:
      url: https://github.com/atsign-foundation/at_libraries.git
      path: at_server_status
      ref: sdk_refactoring
      version: ^2.0.0

  at_utils:
    git:
      url: https://github.com/atsign-foundation/at_tools.git
      path: at_utils
      ref: sdk_refactoring
      version: ^2.0.1
  at_commons:
    git:
      url: https://github.com/atsign-foundation/at_tools.git
      path: at_commons
      ref: sdk_refactoring
      version: ^2.0.1
  at_persistence_spec:
    git:
      url: https://github.com/atsign-foundation/at_server.git
      path: at_persistence/at_persistence_spec
      ref: sdk_refactoring
      version: ^2.0.0
  at_persistence_secondary_server:
    git:
      url: https://github.com/atsign-foundation/at_server.git
      path: at_secondary/at_persistence_secondary_server
      ref: sdk_refactoring
      version: ^2.0.0

  # at_lookup:
  #   git:
  #     url: https://github.com/atsign-foundation/at_libraries.git
  #     path: at_lookup
  #     ref: connection_issue
  #     version: ^1.0.0+9

  # at_utils:
  #   git:
  #     url: https://github.com/atsign-foundation/at_tools.git
  #     path: at_utils
  #     ref: connection_issue
  #     version: ^1.0.1+8
  # at_commons:
  #   git:
  #     url: https://github.com/atsign-foundation/at_tools.git
  #     path: at_commons
  #     ref: connection_issue
  #     version: ^1.0.1+8

#  at_client_mobile:
#    path: /home/keerthi/Desktop/at_client_sdk/at_client_mobile

flutter:
  assets:
    - assets/
  uses-material-design: true